pub enum Text {
    UnknownCommand,
    UnknownTitle,
    Artist,
    Author,
    Duration,
    QueueLength,
    NowPlaying,
    AddedToQueue,
    Queue,
    FailedToFetch,
    FailedToJoin,
    FailedToPlay,
    CommandOnlyInGuild,
    UserMustBeInVoiceChannel,
    BotMustBeInVoiceChannel,
    QueueEmpty,
    FailedToSkip,
    Skipped,
    Shuffled,
    Disconnected,
    FailedToDisconnect,
    ClearedQueue,
    FailedToChangeChannel,
    ChangedChannel,
    NoSuchFile,
}

impl Text {
    pub fn localization(&self, lang: &String) -> String {
        match lang.as_str() {
            "pl" => match self {
                Text::UnknownCommand => "Nieznane polecenie".to_string(),
                Text::UnknownTitle => "Nieznany tytuł".to_string(),
                Text::Artist => "Artysta".to_string(),
                Text::Author => "Autor".to_string(),
                Text::Duration => "Czas trwania".to_string(),
                Text::QueueLength => "Długość kolejki".to_string(),
                Text::NowPlaying => "Teraz odtwarzane".to_string(),
                Text::AddedToQueue => "Dodano do kolejki".to_string(),
                Text::Queue => "Kolejka".to_string(),
                Text::FailedToFetch => "Nie udało się pobrać informacji o utworze".to_string(),
                Text::FailedToJoin => "Nie udało się dołączyć do kanału głosowego".to_string(),
                Text::FailedToPlay => "Nie udało się odtworzyć utworu".to_string(),
                Text::CommandOnlyInGuild => "To polecenie może być używane tylko na serwerze.".to_string(),
                Text::UserMustBeInVoiceChannel => "Musisz być na kanale głosowym.".to_string(),
                Text::BotMustBeInVoiceChannel => "Bot musi być na kanale głosowym.".to_string(),
                Text::QueueEmpty => "Kolejka jest pusta.".to_string(),
                Text::FailedToSkip => "Nie udało się pominąć utworu.".to_string(),
                Text::Skipped => "Utwór pominięty.".to_string(),
                Text::Shuffled => "Kolejka została przetasowana.".to_string(),
                Text::Disconnected => "Rozłączono.".to_string(),
                Text::FailedToDisconnect => "Nie udało się rozłączyć.".to_string(),
                Text::ClearedQueue => "Kolejka została wyczyszczona.".to_string(),
                Text::FailedToChangeChannel => "Nie udało się zmienić kanału głosowego.".to_string(),
                Text::ChangedChannel => "Zmieniono kanał głosowy.".to_string(),
                Text::NoSuchFile => "Nie znaleziono takiego pliku.".to_string(),
            },
            _ => match self {
                Text::UnknownCommand => "Unknown command".to_string(),
                Text::UnknownTitle => "Unknown title".to_string(),
                Text::Artist => "Artist".to_string(),
                Text::Author => "Author".to_string(),
                Text::Duration => "Duration".to_string(),
                Text::QueueLength => "Queue length".to_string(),
                Text::NowPlaying => "Now playing".to_string(),
                Text::AddedToQueue => "Added to queue".to_string(),
                Text::Queue => "Queue".to_string(),
                Text::FailedToFetch => "Failed to fetch track info".to_string(),
                Text::FailedToJoin => "Failed to join voice channel".to_string(),
                Text::FailedToPlay => "Failed to play track".to_string(),
                Text::CommandOnlyInGuild => "This command can only be used in a server.".to_string(),
                Text::UserMustBeInVoiceChannel => "You must be in a voice channel.".to_string(),
                Text::BotMustBeInVoiceChannel => "Bot must be in a voice channel.".to_string(),
                Text::QueueEmpty => "Queue is empty.".to_string(),
                Text::FailedToSkip => "Failed to skip track.".to_string(),
                Text::Skipped => "Track skipped.".to_string(),
                Text::Shuffled => "Queue shuffled.".to_string(),
                Text::Disconnected => "Disconnected.".to_string(),
                Text::FailedToDisconnect => "Failed to disconnect.".to_string(),
                Text::ClearedQueue => "Cleared queue.".to_string(),
                Text::FailedToChangeChannel => "Failed to change voice channel.".to_string(),
                Text::ChangedChannel => "Changed voice channel.".to_string(),
                Text::NoSuchFile => "No such file found.".to_string(),
            },
        }
    }
}