name: Nightly Release

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: musicbot

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Build
      run: cargo build --release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Nightly build
        files: |
          target/release/${{ env.BINARY_NAME }}
          target/release/${{ env.BINARY_NAME }}.exe
        overwrite_files: true
        make_latest: true
