name: Nightly Release

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: musicbot

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust (stable)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Build (release)
      run: cargo build --release

    - name: Package
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          powershell -Command "Compress-Archive -Path target/release/${{ env.BINARY_NAME }}.exe -DestinationPath ${ { env.BINARY_NAME } }-windows.zip"
        else
          tar -czf ${{ env.BINARY_NAME }}-linux.tar.gz -C target/release ${{ env.BINARY_NAME }}
        fi
      shell: bash

    - name: Release (create/update) & upload assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Nightly build
        files: |
          ${{ env.BINARY_NAME }}-linux.tar.gz
          ${{ env.BINARY_NAME }}-windows.zip
          target/release/${{ env.BINARY_NAME }}*
        overwrite_files: true
        make_latest: true
